# Placeholder docker-compose configuration
# Will be implemented later 

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/mlruns:ro
    environment:
      - PYTHONPATH=/app
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 