name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run flake8
      run: |
        flake8 src/ tests/ --max-line-length=100 --exclude=__pycache__
        
    - name: Run tests
      run: |
        pytest tests/ -v --cov=src
        
    - name: Build Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker build -t credit-risk-api .
        
    - name: Test Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker run -d -p 8000:8000 --name test-api credit-risk-api
        sleep 5
        curl -f http://localhost:8000/
